#!/usr/bin/env bash
# Download the article cover images from the current EVO site into this repo.
#
# The build environment these files were prepared in cannot fetch binary assets, so
# the images could not be pulled down automatically. Run this once from anywhere with
# internet access — a GitHub Codespace is ideal — then commit what it downloads.
#
#   bash tools/fetch-article-images.sh

set -u
cd "$(dirname "$0")/.." || exit 1
mkdir -p public/images/insights
ok=0; fail=0

if curl -fsSL "https://evo-pm.com/media/3pkdfui1/kal137_evo_a-guide-to-housing-standards-in-the-uk_kal051_evo_-a-guide-to-hmo-for-landlords-articlecover.jpg" -o "public/images/insights/a-guide-to-housing-standards-in-the-uk.jpg" ; then ok=$((ok+1)); else echo "FAILED: a-guide-to-housing-standards-in-the-uk"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/pbnljuzg/kal074_evo_property-ombudsman-articlecover.png" -o "public/images/insights/a-landlord-s-guide-on-how-to-make-a-property-inventory.png" ; then ok=$((ok+1)); else echo "FAILED: a-landlord-s-guide-on-how-to-make-a-property-inventory"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/wsnjdycb/kal138_evo_how-to-spot-and-treat-rising-dampness-articlecover.jpg" -o "public/images/insights/a-landlord-s-guide-on-how-to-spot-and-treat-rising-damp.jpg" ; then ok=$((ok+1)); else echo "FAILED: a-landlord-s-guide-on-how-to-spot-and-treat-rising-damp"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/c35hgvi3/kal148_evo_accessible-housing_articlecover_kal051_evo_-a-guide-to-hmo-for-landlords-articlecover.jpg" -o "public/images/insights/accessible-housing-adapting-disabled-residents-properties.jpg" ; then ok=$((ok+1)); else echo "FAILED: accessible-housing-adapting-disabled-residents-properties"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/4zwpa45d/kal053_evo_-pestcontrol-articlecover-2.png" -o "public/images/insights/are-landlords-responsible-for-pest-control-uk.png" ; then ok=$((ok+1)); else echo "FAILED: are-landlords-responsible-for-pest-control-uk"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/d0id3u50/kal193_evo_awaabs-law.jpg" -o "public/images/insights/awaab-s-law-how-social-housing-providers-can-comply.jpg" ; then ok=$((ok+1)); else echo "FAILED: awaab-s-law-how-social-housing-providers-can-comply"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/lucbfhkc/kal077_evo_landlord-insurance-articlecover.png" -o "public/images/insights/best-landlord-insurance-uk-which-one-is-best-for-you-in-2023.png" ; then ok=$((ok+1)); else echo "FAILED: best-landlord-insurance-uk-which-one-is-best-for-you-in-2023"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/q5dj0c1e/cas.jpeg" -o "public/images/insights/case-study-evo-and-bd-reside.jpeg" ; then ok=$((ok+1)); else echo "FAILED: case-study-evo-and-bd-reside"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/edvfbj2s/kal051_evo_-a-guide-to-hmo-for-landlords-articlecover-2.png" -o "public/images/insights/do-i-need-an-hmo-licence-for-three-tenants-landlord-hmo-guide.png" ; then ok=$((ok+1)); else echo "FAILED: do-i-need-an-hmo-licence-for-three-tenants-landlord-hmo-guide"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/jmphkbtl/kal073_evo_abestos-articlecover.png" -o "public/images/insights/duty-to-manage-asbestos-everything-landlords-and-tenants-need-to-know.png" ; then ok=$((ok+1)); else echo "FAILED: duty-to-manage-asbestos-everything-landlords-and-tenants-need-to-know"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/3qppyz44/image-for-kal20_evo_electrical-installation-condition-report-v2.jpg" -o "public/images/insights/electrical-installation-condition-report-eicr-guidance-what-landlords-need-to-know-in-2025.jpg" ; then ok=$((ok+1)); else echo "FAILED: electrical-installation-condition-report-eicr-guidance-what-landlords-need-to-know-in-2025"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/zesbawcx/image-for-kal029_evo_extended-regulations-on-domestic-smoke-notitle.jpg" -o "public/images/insights/extended-regulations-on-domestic-smoke-and-carbon-monoxide-alarms.jpg" ; then ok=$((ok+1)); else echo "FAILED: extended-regulations-on-domestic-smoke-and-carbon-monoxide-alarms"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/su5cfypy/image-for-kal028_evo_landlord-news_notitle.jpg" -o "public/images/insights/failing-landlords-to-expect-ofsted-style-inspections-and-unlimited-fines.jpg" ; then ok=$((ok+1)); else echo "FAILED: failing-landlords-to-expect-ofsted-style-inspections-and-unlimited-fines"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/gbrkme4s/kal144_evo_renting-furnished-property_articlecover.jpg" -o "public/images/insights/furnished-or-unfurnished-which-is-best-for-landlords-to-rent.jpg" ; then ok=$((ok+1)); else echo "FAILED: furnished-or-unfurnished-which-is-best-for-landlords-to-rent"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/50jmjfcj/image-for-kal19_evo_gas-safe-building-compliance-regulations-notitle.jpg" -o "public/images/insights/gas-safe-building-compliance-regulations-certificate-what-landlords-need-to-know-in-2025.jpg" ; then ok=$((ok+1)); else echo "FAILED: gas-safe-building-compliance-regulations-certificate-what-landlords-need-to-know-in-2025"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/af1bqf5q/kal142_evo_hhsrs_tombstone-articlecover-1.jpg" -o "public/images/insights/hhsrs-inspection-what-it-is-what-to-expect-and-how-to-avoid-one.jpg" ; then ok=$((ok+1)); else echo "FAILED: hhsrs-inspection-what-it-is-what-to-expect-and-how-to-avoid-one"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/3pkdfui1/kal137_evo_a-guide-to-housing-standards-in-the-uk_kal051_evo_-a-guide-to-hmo-for-landlords-articlecover.jpg" -o "public/images/insights/housing-association-garden-rules-how-to-work-with-residents-for-better-gardens.jpg" ; then ok=$((ok+1)); else echo "FAILED: housing-association-garden-rules-how-to-work-with-residents-for-better-gardens"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/hb3k2hrj/kal132_evo_housing-management-systems.jpg" -o "public/images/insights/housing-management-systems-how-to-effectively-manage-your-portfolio.jpg" ; then ok=$((ok+1)); else echo "FAILED: housing-management-systems-how-to-effectively-manage-your-portfolio"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/pbnljuzg/kal074_evo_property-ombudsman-articlecover.png" -o "public/images/insights/how-can-resident-satisfaction-be-gauged.png" ; then ok=$((ok+1)); else echo "FAILED: how-can-resident-satisfaction-be-gauged"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/iqmb4tgs/kal229_evo_how-long-do-landlords-have-to-fix-problems-uk-1.jpg" -o "public/images/insights/how-long-do-landlords-have-to-fix-problems-in-the-uk.jpg" ; then ok=$((ok+1)); else echo "FAILED: how-long-do-landlords-have-to-fix-problems-in-the-uk"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/pbnljuzg/kal074_evo_property-ombudsman-articlecover.png" -o "public/images/insights/how-many-warnings-before-eviction-uk-a-guide-to-the-eviction-process-for-landlords-and-housing-associations.png" ; then ok=$((ok+1)); else echo "FAILED: how-many-warnings-before-eviction-uk-a-guide-to-the-eviction-process-for-landlords-and-housing-associations"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/1m2l0knk/image-for-kal027_evo_property-management-agencies-1.jpg" -o "public/images/insights/how-to-choose-the-right-property-management-company.jpg" ; then ok=$((ok+1)); else echo "FAILED: how-to-choose-the-right-property-management-company"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/cjglixsm/kal261_evo_how-to-protect-your-property-during-heatwaves.jpg" -o "public/images/insights/how-to-protect-your-property-during-heatwaves.jpg" ; then ok=$((ok+1)); else echo "FAILED: how-to-protect-your-property-during-heatwaves"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/hitd3q43/kal201_evo_-how-to-set-up-a-housing-association-repairs-policy.jpg" -o "public/images/insights/how-to-set-up-a-housing-association-repairs-and-maintenance-policy.jpg" ; then ok=$((ok+1)); else echo "FAILED: how-to-set-up-a-housing-association-repairs-and-maintenance-policy"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/5jzlv02z/kal046_evo_guide-for-landlords-articlecover-3.jpg" -o "public/images/insights/landlord-inspection-checklist-a-guide-for-landlords.jpg" ; then ok=$((ok+1)); else echo "FAILED: landlord-inspection-checklist-a-guide-for-landlords"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/khwl2wfw/kal161_evo_landlord-legal-requirements.jpg" -o "public/images/insights/landlord-legal-requirements-a-checklist-for-social-housing-providers.jpg" ; then ok=$((ok+1)); else echo "FAILED: landlord-legal-requirements-a-checklist-for-social-housing-providers"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/g21d2odq/kal099_evo_damp-mould_article-cover.jpg" -o "public/images/insights/landlord-mould-responsibility-a-complete-guide.jpg" ; then ok=$((ok+1)); else echo "FAILED: landlord-mould-responsibility-a-complete-guide"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/b0ahr1q1/kal246_evo_renters-rights-bill-202-1.jpg" -o "public/images/insights/renters-rights-bill-2025-when-will-extensive-reforms-become-law.jpg" ; then ok=$((ok+1)); else echo "FAILED: renters-rights-bill-2025-when-will-extensive-reforms-become-law"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/0defs4b5/kal218_evo_renters-rights-bill.jpg" -o "public/images/insights/renters-rights-bill-how-are-labour-s-plans-for-private-rented-housing-different.jpg" ; then ok=$((ok+1)); else echo "FAILED: renters-rights-bill-how-are-labour-s-plans-for-private-rented-housing-different"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/gjybnpj3/kal043_evo_everything-landlords-and-tenants-articlecover-2.jpg" -o "public/images/insights/section-8-grounds-everything-you-need-to-know.jpg" ; then ok=$((ok+1)); else echo "FAILED: section-8-grounds-everything-you-need-to-know"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/14smidqj/kal253_evo_social-posts-social-housing-investment.jpg" -o "public/images/insights/social-housing-investment-why-money-isn-t-everything.jpg" ; then ok=$((ok+1)); else echo "FAILED: social-housing-investment-why-money-isn-t-everything"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/pundh40l/kal241_evo_families-locked-out-of-affordable-homes-for-generations-social-posts.jpg" -o "public/images/insights/social-housing-uk-families-locked-out-of-affordable-homes-for-generations.jpg" ; then ok=$((ok+1)); else echo "FAILED: social-housing-uk-families-locked-out-of-affordable-homes-for-generations"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/edvfbj2s/kal051_evo_-a-guide-to-hmo-for-landlords-articlecover-2.png" -o "public/images/insights/tenant-checks-for-landlords-how-social-housing-providers-can-screen-residents.png" ; then ok=$((ok+1)); else echo "FAILED: tenant-checks-for-landlords-how-social-housing-providers-can-screen-residents"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/fqqpcc3o/kal168_evo_tenant-satisfaction-measures_kal051_evo_-a-guide-to-hmo-for-landlords-articlecover.jpg" -o "public/images/insights/tenant-satisfaction-measures-a-guide-for-housing-providers.jpg" ; then ok=$((ok+1)); else echo "FAILED: tenant-satisfaction-measures-a-guide-for-housing-providers"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/ppvp1ds5/kal030_evo_the-renters-reform-bill-2022-notext.jpeg" -o "public/images/insights/the-renters-reform-bill-2023-everything-you-need-to-know.jpeg" ; then ok=$((ok+1)); else echo "FAILED: the-renters-reform-bill-2023-everything-you-need-to-know"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/124puvoi/tenexp.png" -o "public/images/insights/the-tenant-experience-and-why-it-matters.png" ; then ok=$((ok+1)); else echo "FAILED: the-tenant-experience-and-why-it-matters"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/qfsj5t3q/kal231_evo_uk-housing-crisis-social-posts.jpg" -o "public/images/insights/the-uk-housing-crisis-causes-impact-and-solutions.jpg" ; then ok=$((ok+1)); else echo "FAILED: the-uk-housing-crisis-causes-impact-and-solutions"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/0bhjmfaw/kal121_evo_the-ultimate-buy-to-let-strategy-and-business-plan-articlecover.png" -o "public/images/insights/the-ultimate-buy-to-let-strategy-and-business-plan.png" ; then ok=$((ok+1)); else echo "FAILED: the-ultimate-buy-to-let-strategy-and-business-plan"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/sdolejyw/kal087_evo_what-is-the-social-housing-decarbonisation-fund-articlecover.png" -o "public/images/insights/warm-homes-social-housing-fund-replaces-the-social-housing-decarbonisation-fund.png" ; then ok=$((ok+1)); else echo "FAILED: warm-homes-social-housing-fund-replaces-the-social-housing-decarbonisation-fund"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/ghvk5dko/kal131_evo_what-checks-do-housing-associations-do_article-cover.jpg" -o "public/images/insights/what-checks-do-housing-associations-do-how-to-find-the-right-accommodation-for-residents.jpg" ; then ok=$((ok+1)); else echo "FAILED: what-checks-do-housing-associations-do-how-to-find-the-right-accommodation-for-residents"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/3ycj1xec/kal117_evo_what-is-an-assured-shorthold-tenancy.jpg" -o "public/images/insights/what-is-an-assured-shorthold-tenancy.jpg" ; then ok=$((ok+1)); else echo "FAILED: what-is-an-assured-shorthold-tenancy"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/a2vmtjps/kal042_evo_planned-preventative-maintenance_articlecover-2.jpg" -o "public/images/insights/what-is-planned-preventative-maintenance.jpg" ; then ok=$((ok+1)); else echo "FAILED: what-is-planned-preventative-maintenance"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/assnz4ak/kal202_evo_-what-is-the-leasehold-reform-act.jpg" -o "public/images/insights/what-is-the-leasehold-and-freehold-reform-act.jpg" ; then ok=$((ok+1)); else echo "FAILED: what-is-the-leasehold-and-freehold-reform-act"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/4bleafec/kal051_evo_-a-guide-to-hmo-for-landlords-articlecover-copy-100.jpg" -o "public/images/insights/what-is-the-pre-action-housing-disrepair-protocol.jpg" ; then ok=$((ok+1)); else echo "FAILED: what-is-the-pre-action-housing-disrepair-protocol"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/pbnljuzg/kal074_evo_property-ombudsman-articlecover.png" -o "public/images/insights/what-is-the-property-ombudsman-code-of-practice.png" ; then ok=$((ok+1)); else echo "FAILED: what-is-the-property-ombudsman-code-of-practice"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/hzujygor/kal075_evo_welcome-pack-articlecover.png" -o "public/images/insights/what-to-include-in-a-tenant-welcome-pack.png" ; then ok=$((ok+1)); else echo "FAILED: what-to-include-in-a-tenant-welcome-pack"; fail=$((fail+1)); fi
if curl -fsSL "https://evo-pm.com/media/xchmucqf/kal186_evo_why-is-the-light-on-my-boiler-flashing.jpg" -o "public/images/insights/why-is-the-light-on-my-boiler-flashing-a-social-housing-resident-s-guide-to-boilers.jpg" ; then ok=$((ok+1)); else echo "FAILED: why-is-the-light-on-my-boiler-flashing-a-social-housing-resident-s-guide-to-boilers"; fail=$((fail+1)); fi

echo
echo "Downloaded $ok, failed $fail."
echo "Now: git add public/images/insights && git commit -m \"Article cover images\" && git push"

# Point the data file at whatever actually downloaded.
if command -v node >/dev/null 2>&1; then
  node tools/link-article-images.mjs
else
  echo "Node not found — run 'node tools/link-article-images.mjs' yourself before building."
fi
